# Generated by Django 4.2.4 on 2023-08-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerceapp", "0006_orders_orderupdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("card_number", models.CharField(max_length=20)),
                ("valid", models.CharField(max_length=100)),
                ("cvv", models.CharField(max_length=3)),
            ],
        ),
    ]
